### ISSUE TITLE
Formfactors for non-proton beams will contain NaNs

### ISSUE THREAD

**Issue by andriish** [LucianHL/SuperChic#103]
The form-factors calculation involve the variables xb1 and xb2, which are initialized only for th proton beams. As a result the xb1 and xb2 will be set to zero for other cases.
The formafactor code contains difisions by xb1 and xb2 and the calculations fail with FPEs.

**Comment by LucianHL** [comment]
This has now been fixed- the offshell calculation was being used, and this is only applicable for hadron beams. Bug introduced when offshell calculation was added
