### ISSUE TITLE
One needs to write a reasonable cross-section for each event.

### ISSUE THREAD

**Issue by andriish** [LucianHL/SuperChic#13]
As of now, the pull request #11 implemented more or less HepMC2-complient output.
However, the cross-section that is written in each event is bogus:

```
write(45,56)'C',1.0d0,0.1d0 !FIXME

```

It would be nice to be able to write there something more reasonable.

**Comment by LucianHL** [comment]
Ok I will have a look

**Comment by andriish** [comment]
Solved.
