### ISSUE TITLE
Pythia 8 version issue 

### ISSUE THREAD

**Issue by LucianHL** [LucianHL/SuperChic#152]
Hi @andriish - the latest pythia update is still not working it seems....

In file included from /unix/theory2/lang/git_sc/Nov20/test/shower.cxx:25:
/unix/theory2/lang/pythia8310/include/Pythia8Plugins/HepMC2.h:23:10: fatal error: HepMC/IO_BaseClass.h: No such file or directory
   23 | #include "HepMC/IO_BaseClass.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~

**Comment by LucianHL** [comment]
Hi @andriish. I am now getting an error due to HepMC/IO_BaseClass.h which it seems is missing?

**Comment by andriish** [comment]
Hi @LucianHL, this ia a part of HepMC2. So you should do `brew install hepmc2` in macOS.

**Comment by andriish** [comment]
Hi @LucianHL , please tell me if that works.

**Comment by LucianHL** [comment]
All sorted, thank you
