### ISSUE TITLE
FPE for AA collisions.

### ISSUE THREAD

**Issue by andriish** [LucianHL/SuperChic#175]
Hi @LucianHL,

in the AA collisions I see FPE
```

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f68f1c5fbaf in ???
	at /usr/src/debug/glibc-2.37-13.fc38.x86_64/signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x492681 in qinit_
	at /home/andriish/Projects/SuperChic/src/diss/qinit.f:27
#2  0x44c750 in cs_
	at /home/andriish/Projects/SuperChic/src/main/main.f:1049
#3  0x42838e in master.0.vegas
	at /home/andriish/Projects/SuperChic/src/int/vegas.f:121
#4  0x40671a in superchic
	at /home/andriish/Projects/SuperChic/src/main/superchic.f:756
#5  0x4024a7 in main
	at /home/andriish/Projects/SuperChic/src/main/superchic.f:944
<end of output>
Test time =  11.90 sec

```

Basically here:
```
      xit=-bq-dsqrt(rootq)
      xit=xit/2d0/aq

```
in src/diss/qinit.f  rootq <0.  

That is a discriminant of some quadratic equation.

Could you, please, have a look?

**Comment by LucianHL** [comment]
I think you are trying to include inelastic photon emission for AA collisions which is not currently supported - just 'el' should be ok though

**Comment by andriish** [comment]
Hi @LucianHL ,

Hm. if you mean the photoproduction in AA, then I have excluded it. And the program ends there with 'STOP' and a reasonable error message. This case is exactly for the 'el'.

**Comment by LucianHL** [comment]
Ok thanks @andriish. This subroutine should only be called for dissociative production I believe so something else is going on here it seems. I will look into it

**Comment by LucianHL** [comment]
Non - el production was indeed being tested for on the latest version - I have updated to remove these and now there are crashes but "only" for showering
