### ISSUE TITLE
More cards are needed.

### ISSUE THREAD

**Issue by andriish** [LucianHL/SuperChic#7]
It would be nice to have more control cards that will run fast and  will test all the cases of output logic in the `unwprint_q.f`.

**Comment by LucianHL** [comment]
Hi Andrii,

I think the default card does this? What would you like changed exactly?

Lucian

**Comment by andriish** [comment]
Hi @LucianHL,

1) sorry for a delay -- had to talk to a student.

2) I mean there are different scenarios in the unwprint_q.f with different number of particles.

```
if(diff.eq.'el')then
```

```
elseif(diff.eq.'dd')then

```

etc.

**Comment by LucianHL** [comment]
Unless it is a big issue I would rather leave the bin with just one input card that the user can modify/multiply offline. It is straightforward to just e.g. change the diff flag, so I am not sure it is necessary to provide a set of ready made inputs?

**Comment by andriish** [comment]
Hi @LucianHL, OK. I found out how to modify the flags and get the other cases. 
So I close the issue. 

Andrii
